# _config.yml
title:  "Korupolu Siri"
description: "My coding journey â€” Python learning notes, problem solving, and projects."
baseurl: "" # keep empty for user site
url: "https://siri-gh2.github.io"

author:
  name: "Korupolu Siri"
  bio: "Computer Science student | Learning Python & Web Dev"
  github: "https://github.com/Siri-gh2"
  linkedin: "https://www.linkedin.com/in/korupolu-siri-247653296?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"

theme: minima
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
permalink: /:categories/:year/:month/:day/:title/
